using Microsoft.AspNetCore.Identity;

namespace SupplierDirectory.Domain;
public abstract class AuditableEntity { public int Id { get; set; } public bool IsDeleted { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime? UpdatedAt { get; set; } }
public sealed class ApplicationUser : IdentityUser { }
public sealed class Area : AuditableEntity { public required string Name { get; set; } public string? Description { get; set; } public int? ParentAreaId { get; set; } public Area? ParentArea { get; set; } public ICollection<Area> Children { get; set; } = []; public bool IsActive { get; set; } = true; public ICollection<SupplierArea> SupplierAreas { get; set; } = []; }
public sealed class Category : AuditableEntity { public required string Name { get; set; } public string? Description { get; set; } public string? ImageUrl { get; set; } public bool IsActive { get; set; } = true; public ICollection<SupplierCategory> SupplierCategories { get; set; } = []; }
public sealed class Supplier : AuditableEntity { public required string Name { get; set; } public string? Description { get; set; } public string? LogoUrl { get; set; } public string? PhoneNumber { get; set; } public string? AdditionalPhoneNumbers { get; set; } public string? WhatsAppNumber { get; set; } public string? Email { get; set; } public string? Website { get; set; } public string? Address { get; set; } public string? ShortAddress { get; set; } public bool HasTechnicians { get; set; } public decimal? Latitude { get; set; } public decimal? Longitude { get; set; } public string? GoogleMapsUrl { get; set; } public bool IsActive { get; set; } = true; public ICollection<SupplierImage> Images { get; set; } = []; public ICollection<SupplierCategory> SupplierCategories { get; set; } = []; public ICollection<SupplierArea> SupplierAreas { get; set; } = []; }
public sealed class SupplierImage : AuditableEntity { public int SupplierId { get; set; } public Supplier Supplier { get; set; } = null!; public required string ImageUrl { get; set; } public int DisplayOrder { get; set; } public int? AreaId { get; set; } public Area? Area { get; set; } }
public sealed class SupplierCategory { public int SupplierId { get; set; } public Supplier Supplier { get; set; } = null!; public int CategoryId { get; set; } public Category Category { get; set; } = null!; }
public sealed class SupplierArea { public int SupplierId { get; set; } public Supplier Supplier { get; set; } = null!; public int AreaId { get; set; } public Area Area { get; set; } = null!; }
public sealed class Advertisement : AuditableEntity { public required string Title { get; set; } public string? Description { get; set; } public string? ImageUrl { get; set; } public string? Link { get; set; } public DateTime? StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsActive { get; set; } = true; public int DisplayOrder { get; set; } public int? AreaId { get; set; } public Area? Area { get; set; } }
public sealed class CompanyInfo : AuditableEntity { public string? CompanyName { get; set; } public string? LogoUrl { get; set; } public string? CoverImageUrl { get; set; } public string? About { get; set; } public string? Mission { get; set; } public string? Vision { get; set; } public string? PlatformDescription { get; set; } public string? PlatformServices { get; set; } public string? ContactPhone { get; set; } public string? WhatsApp { get; set; } public string? Email { get; set; } public string? Website { get; set; } public string? SocialLinksJson { get; set; } }


