using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplierDirectory.Application;
using SupplierDirectory.Domain;
using SupplierDirectory.Infrastructure;
namespace SupplierDirectory.Controllers;
[ApiController, Route("api/admin"), Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme, Roles="Admin")]
public sealed class AdminController(AppDbContext db, IFileStorageService files, ILogger<AdminController> log) : ControllerBase {
 [HttpGet("suppliers")] public async Task<IActionResult> Suppliers([FromQuery] SupplierQuery q){var x=db.Suppliers.AsNoTracking();if(!string.IsNullOrWhiteSpace(q.Search))x=x.Where(s=>s.Name.Contains(q.Search));var total=await x.CountAsync();var data=await x.OrderByDescending(s=>s.CreatedAt).Skip((q.Page-1)*q.PageSize).Take(q.PageSize).Select(s=>new{s.Id,s.Name,s.IsActive,s.LogoUrl,s.CreatedAt,Categories=s.SupplierCategories.Select(c=>c.Category.Name),Areas=s.SupplierAreas.Select(a=>a.Area.Name)}).ToListAsync();var p=new PageResult<object>(data.Cast<object>().ToList(),q.Page,q.PageSize,total);return Ok(new ApiResponse<object>(true,"تم الاسترجاع",p.Items,p.Meta));}
 [HttpPost("suppliers")] public async Task<IActionResult> CreateSupplier(SupplierRequest r){var s=new Supplier{Name=r.Name,Description=r.Description,PhoneNumber=r.PhoneNumber,AdditionalPhoneNumbers=r.AdditionalPhoneNumbers,WhatsAppNumber=r.WhatsAppNumber,Email=r.Email,Website=r.Website,Address=r.Address,Latitude=r.Latitude,Longitude=r.Longitude,GoogleMapsUrl=r.GoogleMapsUrl,IsActive=r.IsActive}; await SetRelations(s,r);db.Suppliers.Add(s);await db.SaveChangesAsync();log.LogInformation("Supplier {SupplierId} created by {User}",s.Id,User.Identity?.Name);return Created($"/api/admin/suppliers/{s.Id}",new ApiResponse<object>(true,"تمت الإضافة",new{id=s.Id}));}
 [HttpPut("suppliers/{id:int}")] public async Task<IActionResult> UpdateSupplier(int id,SupplierRequest r){var s=await db.Suppliers.Include(x=>x.SupplierAreas).Include(x=>x.SupplierCategories).FirstOrDefaultAsync(x=>x.Id==id);if(s is null)return NotFound();s.Name=r.Name;s.Description=r.Description;s.PhoneNumber=r.PhoneNumber;s.AdditionalPhoneNumbers=r.AdditionalPhoneNumbers;s.WhatsAppNumber=r.WhatsAppNumber;s.Email=r.Email;s.Website=r.Website;s.Address=r.Address;s.Latitude=r.Latitude;s.Longitude=r.Longitude;s.GoogleMapsUrl=r.GoogleMapsUrl;s.IsActive=r.IsActive;await SetRelations(s,r);await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم التحديث",new{id}));}
 [HttpDelete("suppliers/{id:int}")] public async Task<IActionResult> DeleteSupplier(int id){var s=await db.Suppliers.FindAsync(id);if(s is null)return NotFound();s.IsDeleted=true;await db.SaveChangesAsync();return NoContent();}
 [HttpPost("suppliers/{id:int}/logo")] public async Task<IActionResult> Logo(int id,IFormFile file){var s=await db.Suppliers.FindAsync(id);if(s is null)return NotFound();await files.DeleteAsync(s.LogoUrl);s.LogoUrl=await files.SaveImageAsync(file,"suppliers/logos",HttpContext.RequestAborted);await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم رفع الشعار",new{s.LogoUrl}));}
 [HttpPost("suppliers/{id:int}/images")] public async Task<IActionResult> Images(int id,List<IFormFile> filesToUpload){var s=await db.Suppliers.Include(x=>x.Images).FirstOrDefaultAsync(x=>x.Id==id);if(s is null)return NotFound();foreach(var f in filesToUpload)s.Images.Add(new SupplierImage{ImageUrl=await files.SaveImageAsync(f,"suppliers/images",HttpContext.RequestAborted),DisplayOrder=s.Images.Count});await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم رفع الصور",s.Images.Select(x=>new{x.Id,x.ImageUrl})));}
 [HttpDelete("supplier-images/{id:int}")] public async Task<IActionResult> DeleteImage(int id){var x=await db.SupplierImages.FindAsync(id);if(x is null)return NotFound();await files.DeleteAsync(x.ImageUrl);db.SupplierImages.Remove(x);await db.SaveChangesAsync();return NoContent();}
 [HttpGet("areas")] public async Task<IActionResult> Areas()=>Ok(new ApiResponse<object>(true,"تم الاسترجاع",await db.Areas.IgnoreQueryFilters().OrderBy(x=>x.Name).ToListAsync()));
 [HttpPost("areas")] public async Task<IActionResult> Area(AreaRequest r){if(r.ParentAreaId.HasValue&&!await db.Areas.AnyAsync(x=>x.Id==r.ParentAreaId))return BadRequest(new ApiResponse<object>(false,"المنطقة الأم غير موجودة",null));var x=new Area{Name=r.Name,Description=r.Description,ParentAreaId=r.ParentAreaId,IsActive=r.IsActive};db.Areas.Add(x);await db.SaveChangesAsync();return Created($"/api/admin/areas/{x.Id}",new ApiResponse<object>(true,"تمت الإضافة",x));}
 [HttpPut("areas/{id:int}")] public async Task<IActionResult> Area(int id,AreaRequest r){if(r.ParentAreaId==id)return BadRequest(new ApiResponse<object>(false,"لا يمكن اختيار المنطقة نفسها كأم",null));var x=await db.Areas.FindAsync(id);if(x is null)return NotFound();x.Name=r.Name;x.Description=r.Description;x.ParentAreaId=r.ParentAreaId;x.IsActive=r.IsActive;await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم التحديث",x));}
 [HttpDelete("areas/{id:int}")] public Task<IActionResult> DeleteArea(int id)=>SoftDelete(db.Areas,id);
 [HttpGet("categories")] public async Task<IActionResult> Categories()=>Ok(new ApiResponse<object>(true,"تم الاسترجاع",await db.Categories.IgnoreQueryFilters().OrderBy(x=>x.Name).ToListAsync()));
 [HttpPost("categories")] public async Task<IActionResult> Category(CategoryRequest r){if(await db.Categories.IgnoreQueryFilters().AnyAsync(x=>x.Name==r.Name))return Conflict(new ApiResponse<object>(false,"اسم التصنيف مستخدم",null));var x=new Category{Name=r.Name,Description=r.Description,IsActive=r.IsActive};db.Categories.Add(x);await db.SaveChangesAsync();return Created($"/api/admin/categories/{x.Id}",new ApiResponse<object>(true,"تمت الإضافة",x));}
 [HttpPut("categories/{id:int}")] public async Task<IActionResult> Category(int id,CategoryRequest r){var x=await db.Categories.FindAsync(id);if(x is null)return NotFound();x.Name=r.Name;x.Description=r.Description;x.IsActive=r.IsActive;await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم التحديث",x));}
 [HttpDelete("categories/{id:int}")] public Task<IActionResult> DeleteCategory(int id)=>SoftDelete(db.Categories,id);
 [HttpPost("advertisements")] public async Task<IActionResult> Ad(AdvertisementRequest r){if(r.EndDate<r.StartDate)return BadRequest(new ApiResponse<object>(false,"تاريخ النهاية يجب أن يكون بعد البداية",null));var x=new Advertisement{Title=r.Title,Description=r.Description,Link=r.Link,StartDate=r.StartDate,EndDate=r.EndDate,IsActive=r.IsActive,DisplayOrder=r.DisplayOrder};db.Advertisements.Add(x);await db.SaveChangesAsync();return Created($"/api/admin/advertisements/{x.Id}",new ApiResponse<object>(true,"تمت الإضافة",x));}
 [HttpPut("advertisements/{id:int}")] public async Task<IActionResult> Ad(int id,AdvertisementRequest r){var x=await db.Advertisements.FindAsync(id);if(x is null)return NotFound();if(r.EndDate<r.StartDate)return BadRequest();x.Title=r.Title;x.Description=r.Description;x.Link=r.Link;x.StartDate=r.StartDate;x.EndDate=r.EndDate;x.IsActive=r.IsActive;x.DisplayOrder=r.DisplayOrder;await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم التحديث",x));}
 [HttpDelete("advertisements/{id:int}")] public Task<IActionResult> DeleteAd(int id)=>SoftDelete(db.Advertisements,id);
 [HttpGet("company")] public async Task<IActionResult> Company()=>Ok(new ApiResponse<object>(true,"تم الاسترجاع",await db.CompanyInfos.FirstOrDefaultAsync()));
 [HttpPut("company")] public async Task<IActionResult> Company(CompanyRequest r){var x=await db.CompanyInfos.FirstOrDefaultAsync()??new CompanyInfo();x.CompanyName=r.CompanyName;x.About=r.About;x.Mission=r.Mission;x.Vision=r.Vision;x.PlatformDescription=r.PlatformDescription;x.PlatformServices=r.PlatformServices;x.ContactPhone=r.ContactPhone;x.WhatsApp=r.WhatsApp;x.Email=r.Email;x.Website=r.Website;x.SocialLinksJson=r.SocialLinksJson;if(x.Id==0)db.CompanyInfos.Add(x);await db.SaveChangesAsync();return Ok(new ApiResponse<object>(true,"تم التحديث",x));}
 async Task SetRelations(Supplier s,SupplierRequest r){var categories=await db.Categories.Where(x=>r.CategoryIds.Contains(x.Id)).Select(x=>x.Id).ToListAsync();var areas=await db.Areas.Where(x=>r.AreaIds.Contains(x.Id)).Select(x=>x.Id).ToListAsync();if(categories.Count!=r.CategoryIds.Distinct().Count()||areas.Count!=r.AreaIds.Distinct().Count())throw new InvalidOperationException("تصنيف أو منطقة غير صالحة");s.SupplierCategories.Clear();s.SupplierAreas.Clear();foreach(var id in categories)s.SupplierCategories.Add(new SupplierCategory{Supplier=s,CategoryId=id});foreach(var id in areas)s.SupplierAreas.Add(new SupplierArea{Supplier=s,AreaId=id});}
 async Task<IActionResult> SoftDelete<T>(DbSet<T> set,int id) where T:AuditableEntity {var x=await set.FindAsync(id);if(x is null)return NotFound();x.IsDeleted=true;await db.SaveChangesAsync();return NoContent();}
}
