using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplierDirectory.Application;
using SupplierDirectory.Domain;
using SupplierDirectory.Infrastructure;
namespace SupplierDirectory.Controllers;
[Authorize(Roles="Admin")]
public sealed class AreasDashboardController(AppDbContext db) : Controller {
 [HttpGet("dashboard/areas")] public async Task<IActionResult> Index([FromQuery] AreaListQuery query){var areas=db.Areas.AsNoTracking();if(!string.IsNullOrWhiteSpace(query.Search))areas=areas.Where(x=>x.Name.Contains(query.Search)|| (x.Description??"").Contains(query.Search));if(query.ParentId.HasValue)areas=areas.Where(x=>x.ParentAreaId==query.ParentId);var total=await areas.CountAsync();var items=await areas.OrderBy(x=>x.ParentAreaId).ThenBy(x=>x.Name).Skip((query.Page-1)*query.PageSize).Take(query.PageSize).Select(x=>new AreaListItem{Id=x.Id,Name=x.Name,Description=x.Description,ParentAreaId=x.ParentAreaId,ParentName=x.ParentArea==null?null:x.ParentArea.Name,IsActive=x.IsActive,CreatedAt=x.CreatedAt}).ToListAsync();return View(new AreaListViewModel{Items=items,Parents=await Parents(),Query=query,TotalCount=total});}
 [HttpGet("dashboard/areas/create")] public async Task<IActionResult> Create()=>View("Form",new AreaFormViewModel{Parents=await Parents()});
 [HttpPost("dashboard/areas/create"),ValidateAntiForgeryToken] public async Task<IActionResult> Create(AreaFormViewModel model){if(model.ParentAreaId.HasValue&&!await db.Areas.AnyAsync(x=>x.Id==model.ParentAreaId))ModelState.AddModelError(nameof(model.ParentAreaId),"المنطقة الأم غير موجودة");if(!ModelState.IsValid){model.Parents=await Parents();return View("Form",model);}db.Areas.Add(new Area{Name=model.Name.Trim(),Description=model.Description?.Trim(),ParentAreaId=model.ParentAreaId,IsActive=model.IsActive});await db.SaveChangesAsync();TempData["Success"]="تمت إضافة المنطقة";return RedirectToAction(nameof(Index));}
 [HttpGet("dashboard/areas/{id:int}/edit")] public async Task<IActionResult> Edit(int id){var x=await db.Areas.FindAsync(id);if(x is null)return NotFound();return View("Form",new AreaFormViewModel{Id=x.Id,Name=x.Name,Description=x.Description,ParentAreaId=x.ParentAreaId,IsActive=x.IsActive,Parents=(await Parents()).Where(p=>p.Id!=id).ToList()});}
 [HttpPost("dashboard/areas/{id:int}/edit"),ValidateAntiForgeryToken] public async Task<IActionResult> Edit(int id,AreaFormViewModel model){var x=await db.Areas.FindAsync(id);if(x is null)return NotFound();if(model.ParentAreaId==id)ModelState.AddModelError(nameof(model.ParentAreaId),"لا يمكن أن تكون المنطقة أمًا لنفسها");if(model.ParentAreaId.HasValue&&!await db.Areas.AnyAsync(a=>a.Id==model.ParentAreaId))ModelState.AddModelError(nameof(model.ParentAreaId),"المنطقة الأم غير موجودة");if(!ModelState.IsValid){model.Id=id;model.Parents=(await Parents()).Where(p=>p.Id!=id).ToList();return View("Form",model);}x.Name=model.Name.Trim();x.Description=model.Description?.Trim();x.ParentAreaId=model.ParentAreaId;x.IsActive=model.IsActive;await db.SaveChangesAsync();TempData["Success"]="تم تعديل المنطقة";return RedirectToAction(nameof(Index));}
 [HttpPost("dashboard/areas/{id:int}/toggle"),ValidateAntiForgeryToken] public async Task<IActionResult> Toggle(int id){var x=await db.Areas.FindAsync(id);if(x is null)return NotFound();x.IsActive=!x.IsActive;await db.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 [HttpPost("dashboard/areas/{id:int}/delete"),ValidateAntiForgeryToken] public async Task<IActionResult> Delete(int id){var x=await db.Areas.FindAsync(id);if(x is null)return NotFound();if(await db.Areas.AnyAsync(a=>a.ParentAreaId==id)||await db.SupplierAreas.AnyAsync(a=>a.AreaId==id)){TempData["Error"]="لا يمكن حذف منطقة مرتبطة بمناطق فرعية أو موردين";return RedirectToAction(nameof(Index));}x.IsDeleted=true;await db.SaveChangesAsync();TempData["Success"]="تم نقل المنطقة إلى سلة المحذوفات";return RedirectToAction(nameof(Index));}
 async Task<IReadOnlyList<(int Id,string Name)>> Parents()=>(await db.Areas.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Name}).ToListAsync()).Select(x=>(x.Id,x.Name)).ToList();
}
