using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplierDirectory.Domain;
using SupplierDirectory.Infrastructure;
namespace SupplierDirectory.Controllers;
public sealed class ManagementRow { public int Id {get;set;} public string Name {get;set;}=""; public string? Description {get;set;} public bool IsActive {get;set;} public DateTime CreatedAt {get;set;} }
public sealed class ManagementPost { public string Type {get;set;}=""; public int? Id {get;set;} public string Name {get;set;}=""; public string? Description {get;set;} public bool IsActive {get;set;}=true; }
[Authorize(Roles="Admin")]
public sealed class DashboardController(AppDbContext db) : Controller {
 public async Task<IActionResult> Index(){ViewBag.Stats=new { Suppliers=await db.Suppliers.CountAsync(),ActiveSuppliers=await db.Suppliers.CountAsync(x=>x.IsActive),Areas=await db.Areas.CountAsync(),Categories=await db.Categories.CountAsync(),Ads=await db.Advertisements.CountAsync(),ActiveAds=await db.Advertisements.CountAsync(x=>x.IsActive)};ViewBag.Suppliers=await db.Suppliers.OrderByDescending(x=>x.CreatedAt).Take(5).ToListAsync();return View();}
 [HttpGet("dashboard/{type}")] public async Task<IActionResult> Manage(string type){type=type.ToLowerInvariant();ViewBag.Type=type;ViewBag.Title=type switch{"suppliers"=>"الموردون","areas"=>"المناطق","categories"=>"التصنيفات","advertisements"=>"الإعلانات",_=>null};if(ViewBag.Title is null)return NotFound();ViewBag.Rows=type switch{"suppliers"=>await db.Suppliers.Select(x=>new ManagementRow{Id=x.Id,Name=x.Name,Description=x.Description,IsActive=x.IsActive,CreatedAt=x.CreatedAt}).ToListAsync(),"areas"=>await db.Areas.Select(x=>new ManagementRow{Id=x.Id,Name=x.Name,Description=x.Description,IsActive=x.IsActive,CreatedAt=x.CreatedAt}).ToListAsync(),"categories"=>await db.Categories.Select(x=>new ManagementRow{Id=x.Id,Name=x.Name,Description=x.Description,IsActive=x.IsActive,CreatedAt=x.CreatedAt}).ToListAsync(),_=>await db.Advertisements.Select(x=>new ManagementRow{Id=x.Id,Name=x.Title,Description=x.Description,IsActive=x.IsActive,CreatedAt=x.CreatedAt}).ToListAsync()};return View("Manage");}
 [HttpPost("dashboard/manage"),ValidateAntiForgeryToken] public async Task<IActionResult> Save(ManagementPost r){if(string.IsNullOrWhiteSpace(r.Name)){TempData["Error"]="الاسم مطلوب";return RedirectToAction(nameof(Manage),new{type=r.Type});}switch(r.Type){case "suppliers":await Save<Supplier>(r,()=>new Supplier{Name=r.Name,Description=r.Description,IsActive=r.IsActive},x=>{x.Name=r.Name;x.Description=r.Description;x.IsActive=r.IsActive;});break;case "areas":await Save<Area>(r,()=>new Area{Name=r.Name,Description=r.Description,IsActive=r.IsActive},x=>{x.Name=r.Name;x.Description=r.Description;x.IsActive=r.IsActive;});break;case "categories":await Save<Category>(r,()=>new Category{Name=r.Name,Description=r.Description,IsActive=r.IsActive},x=>{x.Name=r.Name;x.Description=r.Description;x.IsActive=r.IsActive;});break;case "advertisements":await Save<Advertisement>(r,()=>new Advertisement{Title=r.Name,Description=r.Description,IsActive=r.IsActive},x=>{x.Title=r.Name;x.Description=r.Description;x.IsActive=r.IsActive;});break;default:return NotFound();}return RedirectToAction(nameof(Manage),new{type=r.Type});}
 [HttpPost("dashboard/manage/delete"),ValidateAntiForgeryToken] public async Task<IActionResult> Delete(string type,int id){switch(type){case "suppliers":await Delete<Supplier>(id);break;case "areas":await Delete<Area>(id);break;case "categories":await Delete<Category>(id);break;case "advertisements":await Delete<Advertisement>(id);break;default:return NotFound();}return RedirectToAction(nameof(Manage),new{type});}
 [HttpGet("dashboard/company")] public async Task<IActionResult> Company()=>View(await db.CompanyInfos.FirstOrDefaultAsync()??new CompanyInfo());
 async Task Save<T>(ManagementPost r,Func<T> create,Action<T> update) where T:AuditableEntity {if(r.Id is int id){var x=await db.Set<T>().FindAsync(id);if(x is null)throw new KeyNotFoundException();update(x);}else db.Set<T>().Add(create());await db.SaveChangesAsync();}
 async Task Delete<T>(int id) where T:AuditableEntity {var x=await db.Set<T>().FindAsync(id);if(x is null)throw new KeyNotFoundException();x.IsDeleted=true;await db.SaveChangesAsync();}
}
